"""TikZ renderer — camera-ready vector output for LaTeX papers.

The output is a standalone document: compile it directly with pdflatex/tectonic, or copy the ``tikzpicture``
environment into a paper. No LaTeX toolchain is required to generate the file itself.
"""

from __future__ import annotations

from torchdiagram.graph import Graph, Node
from torchdiagram.renderers._format import length
from torchdiagram.theme import DEFAULT, Theme

# Theme color fields mapped to the xcolor names emitted into the preamble.
_COLOR_NAMES = {
    "block_fill": "tdBlockFill",
    "block_stroke": "tdBlockStroke",
    "block_text": "tdBlockText",
    "io_fill": "tdIoFill",
    "io_stroke": "tdIoStroke",
    "io_text": "tdIoText",
    "edge_color": "tdEdgeColor",
    "shape_text": "tdShapeText",
}

# Characters LaTeX would otherwise interpret, mapped to the command that typesets them literally.
_ESCAPES = {
    "\\": r"\textbackslash{}",
    "~": r"\textasciitilde{}",
    "^": r"\textasciicircum{}",
    "×": r"$\times$",
    **{char: f"\\{char}" for char in "{}_#&$%"},
}


def to_tikz(graph: Graph, *, theme: Theme = DEFAULT) -> str:
    """Render ``graph`` as a standalone LaTeX/TikZ document string.

    Args:
        graph: Graph to render, in execution order.
        theme: Colors and typography to apply. Defaults to :data:`torchdiagram.theme.DEFAULT`. The ``font_family`` field
            is ignored here; TikZ uses the LaTeX document font.

    Returns:
        A complete, compilable LaTeX document as a string. Labels are escaped for LaTeX.
    """
    index = {node.id: i for i, node in enumerate(graph.nodes)}
    lines = _preamble(theme)

    previous = None
    for node in graph.nodes:
        style = "io" if node.is_io else "block"
        placement = f", below=of {previous}" if previous else ""
        lines.append(rf"\node[{style}{placement}] ({node.id}) {{{_node_text(node)}}};")
        previous = node.id

    for edge in graph.edges:
        if index[edge.target] - index[edge.source] == 1:
            lines.append(rf"\draw[arrow] ({edge.source}) -- ({edge.target});")
        else:
            lines.append(rf"\draw[arrow] ({edge.source}.east) to[bend left=60] ({edge.target}.east);")

    lines += [r"\end{tikzpicture}", r"\end{document}", ""]
    return "\n".join(lines)


def _preamble(theme: Theme) -> list[str]:
    """Build the document preamble, defining a named xcolor per theme color and the node styles."""
    colors = [
        rf"\definecolor{{{name}}}{{HTML}}{{{getattr(theme, field).removeprefix('#').upper()}}}"
        for field, name in _COLOR_NAMES.items()
    ]
    corner = length(theme.corner_radius)
    line_width = length(theme.stroke_width)
    return [
        "% Generated by torchdiagram",
        r"\documentclass[tikz,border=8pt]{standalone}",
        r"\usetikzlibrary{arrows.meta,positioning}",
        *colors,
        r"\begin{document}",
        r"\begin{tikzpicture}[",
        rf"  block/.style={{draw=tdBlockStroke, rounded corners={corner}pt, fill=tdBlockFill, text=tdBlockText,",
        rf"    line width={line_width}pt, minimum width=32mm, minimum height=8mm, font=\small, align=center}},",
        r"  io/.style={block, fill=tdIoFill, draw=tdIoStroke, text=tdIoText},",
        r"  arrow/.style={-{Stealth[length=2.2mm]}, draw=tdEdgeColor},",
        r"  node distance=7mm and 10mm]",
    ]


def _node_text(node: Node) -> str:
    """Build the LaTeX label text for a node, including its output shape if known."""
    text = _escape(node.label)
    if node.output_shape is not None:
        shape = r"$\times$".join(str(dim) for dim in node.output_shape)
        text += rf"\\ \scriptsize \textcolor{{tdShapeText}}{{{shape}}}"
    return text


def _escape(text: str) -> str:
    """Escape LaTeX special characters in diagram labels.

    Args:
        text: Raw label text.

    Returns:
        Text safe to embed in a LaTeX document.
    """
    return "".join(_ESCAPES.get(char, char) for char in text)
