"""TikZ renderer — camera-ready vector output for LaTeX papers.

The output is a standalone document: compile it directly with pdflatex/tectonic, or copy the ``tikzpicture``
environment into a paper. No LaTeX toolchain is required to generate the file itself.
"""

from __future__ import annotations

from torchdiagram.graph import Graph, Node

_PREAMBLE = [
    "% Generated by torchdiagram",
    r"\documentclass[tikz,border=8pt]{standalone}",
    r"\usetikzlibrary{arrows.meta,positioning}",
    r"\begin{document}",
    r"\begin{tikzpicture}[",
    r"  block/.style={draw=black!60, rounded corners=2pt, fill=black!5,",
    r"    minimum width=32mm, minimum height=8mm, font=\small, align=center},",
    r"  io/.style={block, fill=white, draw=black!40},",
    r"  arrow/.style={-{Stealth[length=2.2mm]}, black!70},",
    r"  node distance=7mm and 10mm]",
]


def to_tikz(graph: Graph) -> str:
    """Render ``graph`` as a standalone LaTeX/TikZ document string.

    Args:
        graph: Graph to render, in execution order.

    Returns:
        A complete, compilable LaTeX document as a string. Labels are escaped for LaTeX.
    """
    index = {node.id: i for i, node in enumerate(graph.nodes)}
    lines = list(_PREAMBLE)

    previous = None
    for node in graph.nodes:
        style = "io" if node.is_io else "block"
        placement = f", below=of {previous}" if previous else ""
        lines.append(rf"\node[{style}{placement}] ({node.id}) {{{_node_text(node)}}};")
        previous = node.id

    for edge in graph.edges:
        if index[edge.target] - index[edge.source] == 1:
            lines.append(rf"\draw[arrow] ({edge.source}) -- ({edge.target});")
        else:
            lines.append(rf"\draw[arrow] ({edge.source}.east) to[bend left=60] ({edge.target}.east);")

    lines += [r"\end{tikzpicture}", r"\end{document}", ""]
    return "\n".join(lines)


def _node_text(node: Node) -> str:
    """Build the LaTeX label text for a node, including its output shape if known."""
    text = _escape(node.label)
    if node.output_shape is not None:
        shape = r"$\times$".join(str(dim) for dim in node.output_shape)
        text += rf"\\ \scriptsize {shape}"
    return text


def _escape(text: str) -> str:
    """Escape LaTeX special characters in diagram labels.

    Args:
        text: Raw label text.

    Returns:
        Text safe to embed in a LaTeX document.
    """
    out = []
    for char in text:
        if char == "\\":
            out.append(r"\textbackslash{}")
        elif char == "~":
            out.append(r"\textasciitilde{}")
        elif char == "^":
            out.append(r"\textasciicircum{}")
        elif char in "{}_#&$%":
            out.append("\\" + char)
        else:
            out.append(char)
    return "".join(out)
